# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:11.6.0
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Dependency Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Build App
          command: yarn build
      - save_cache:
          name: Cache Build Folder
          key: v1-build-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - build
  deploy:
    working_directory: ~/repo
    machine:
      enabled: true
    steps:
      - restore_cache:
          key: v1-build-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run: ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts 
      - run: sudo apt-get update && sudo apt-get install rsync
      - run: rsync -va --delete build/ $SSH_USER@$SSH_HOST:~/www/
      

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master